import type { Metadata } from "next";
import { Source_Code_Pro, Source_Sans_3 } from "next/font/google";
import "./globals.css";

const sourceCodePro = Source_Code_Pro({
	subsets: ["latin"],
	variable: "--font-code",
});

const sourceSansPro = Source_Sans_3({
	subsets: ["latin"],
	weight: ["400", "700", "800"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sourceCodePro.variable} ${sourceSansPro.variable} antialiased`}>
				<div className={"font-primary bg-slate-900 min-h-screen"}>{children}</div>
			</body>
		</html>
	);
}
